#!/usr/bin/env bash
# Usage: helmfileenv uninstall <version>
# Summary: Uninstall the specified version of helmfile

[ -n "${HELMFILEENV_DEBUG}" ] && set -x
source ${HELMFILEENV_ROOT}/libexec/helpers.sh

[ ${#} -gt 1 ] && error_and_die "usage: helmfileenv uninstall [<version>]"

declare version

if [ -z "${1}" ]; then
  version_file="$(helmfileenv-version-file)"
  if [ "${version_file}" != "${HELMFILEENV_ROOT}/version" ];then
    version="$(cat ${version_file} || true)"
  fi
else
  version="${1}"
fi

[ -n "${version}" ] || error_and_die "Version is not specified"

dst_path="${HELMFILEENV_ROOT}/versions/${version}"
if [ -f "${dst_path}/bin/helmfile" ]; then
  info "Uninstall helmfile v${version}"
  rm -r "${dst_path}"
  info "\033[0;32mhelmfile v${version} is successfully uninstalled\033[0;39m"
fi
