#!/usr/bin/env bash
# Summary: Show the current helmfile version
set -e
[ -n "$HELMFILEENV_DEBUG" ] && set -x

if [ -z "$HELMFILEENV_VERSION" ]; then
  HELMFILEENV_VERSION_FILE="$(helmfileenv-version-file)"
  HELMFILEENV_VERSION="$(helmfileenv-version-file-read "$HELMFILEENV_VERSION_FILE" || true)"
fi

if [ -z "$HELMFILEENV_VERSION" ] || [ "$HELMFILEENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${HELMFILEENV_ROOT}/versions/${version}" ]
}

if version_exists "$HELMFILEENV_VERSION"; then
  echo "$HELMFILEENV_VERSION"
elif version_exists "${HELMFILEENV_VERSION#helmfile-}"; then
  echo "${HELMFILEENV_VERSION#helmfile-}"
else
  echo "helmfileenv: version \`$HELMFILEENV_VERSION' is not installed (set by $(helmfileenv-version-origin))" >&2
  exit 1
fi
