#!/usr/bin/env bash
#
# Summary: Run helmfile with the selected version
#
# Usage: helmfileenv exec <command> [arg1 arg2...]
#
# Runs helmfile by first preparing PATH so that the selected
# version's `bin' directory is at the front.
#
# For example, if the currently selected helmfile version is 1.11.3:
#   helmfileenv exec helmfile version
#
# is equivalent to:
#   PATH="$HELMFILEENV_ROOT/versions/1.11.3/bin:$PATH" helmfile version

set -e
[ -n "${HELMFILEENV_DEBUG}" ] && set -x

export CMD=$1
if [ -z "${CMD}" ]; then
  echo "helmfileenv: command is not specified" >&2
  exit 1
fi

shift

export BIN_PATH=$(helmfileenv-bin-path)
if [ -z "${BIN_PATH}" ]; then
  exit 1
fi

export CMD_FULL="${BIN_PATH}/${CMD}"
if [ ! -x "${CMD_FULL}" ]; then
  exit 1
fi

exec "${CMD_FULL}" "${@}"
