#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific helmfile version
#
# Usage: helmfileenv local <version>
#        helmfileenv local --unset
#
# Sets the local application-specific helmfile version by writing the
# version name to a file named `.helmfile-version'.
#
# When you run a helmfile command, helmfileenv will look for a `.helmfile-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, helmfileenv will use the global helmfile version
# specified with `helmfileenv global'. A version specified with the
# `HELMFILEENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a helmfile version known to helmfileenv.
# The special version string `system' will use your default system helmfile.
# Run `helmfileenv versions' for a list of available helmfile versions.

set -e
[ -n "$HELMFILEENV_DEBUG" ] && set -x

# Provide helmfileenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec helmfileenv-versions --bare
fi

HELMFILEENV_VERSION="$1"

if [ "$HELMFILEENV_VERSION" = "--unset" ]; then
  rm -f .helmfile-version
elif [ -n "$HELMFILEENV_VERSION" ]; then
  helmfileenv-version-file-write .helmfile-version "$HELMFILEENV_VERSION"
else
  if version_file="$(helmfileenv-version-file "$PWD")"; then
    helmfileenv-version-file-read "$version_file"
  else
    echo "helmfileenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
